### PR TITLE
Created feed.html and loader js file to represent messages on an html

### PR DESCRIPTION
**Pull request by Ajide49**
I added a new html file and js file to create a page where all the messages will go to.

### CODE REVIEW

**Review by kassidywebb — CHANGES_REQUESTED** [review]
This looks great! I appreciate how consise and organized everything is and the size of the request is perfect. The only change I would suggest would be to put a comment above the buildMessageDiv function explaining what it does and how it works. I know it seems pretty explainatory, but when we start expanding our code, it’ll make it easier to quickly understand fuctions without having to read the entire function.

**Comment by Ajide49** [comment]
> This looks great! I appreciate how consise and organized everything is and the size of the request is perfect. The only change I would suggest would be to put a comment above the buildMessageDiv function explaining what it does and how it works. I know it seems pretty explainatory, but when we start expanding our code, it’ll make it easier to quickly understand fuctions without having to read the entire function.

I went ahead and added a comment for the function!

**Review by imanityson — COMMENTED** [review]
Good! The comments describe the functions well. It looks like everything is consise and everything is pretty straight foward. Good job!

**Review by kassidywebb — APPROVED** [review]

**Comment by vado21** [comment]
Excellent job, I like how you add a new js for the html page to be more organized in the code. Also like how you work on the js script (feed-loader), creating for each appendchild a new function for that.

**Review by vado21 — APPROVED** [review]
Excelent work onthe feed.html

**Review by vado21 — APPROVED** [review]
Correct! We must comment our code and each function.

**Review by imanityson — APPROVED** [review]

**Pull request merged**
